import { useUserStore } from '../store/userStore'

export type TranslationKey = keyof typeof translations.ru

const translations = {
  ru: {
    // Nav
    nav_dashboard: 'Дашборд',
    nav_calculator: 'Налоговый калькулятор',
    nav_salary: 'Зарплатный калькулятор',
    nav_employees: 'Служители / Образец 1',
    nav_accounting: 'Бухгалтерия',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Отчёты и декларации',
    nav_assistant: 'AI Ассистент',
    nav_settings: 'Настройки',
    // Dashboard
    dashboard_title: 'Дашборд',
    dashboard_next_deadline: 'Ближайший дедлайн',
    dashboard_legal_form: 'Правовая форма',
    dashboard_no_deadlines: 'Нет предстоящих дедлайнов',
    // Calculator
    calc_title: 'Налоговый калькулятор',
    calc_income: 'Доход (€)',
    calc_taxable: 'Налогооблагаемая база',
    calc_tax: 'Налог',
    calc_net: 'Чистая прибыль',
    // Salary
    salary_title: 'Зарплатный калькулятор',
    salary_gross: 'Брутто (€)',
    salary_employee_contrib: 'Осигуровки работник',
    salary_employer_contrib: 'Осигуровки работодател',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нетто (€)',
    salary_total_cost: 'Общ разход работодател (€)',
    // Accounting
    accounting_title: 'Бухгалтерия',
    accounting_add: 'Добавить транзакцию',
    accounting_description: 'Описание',
    accounting_amount: 'Сумма (€)',
    accounting_no_transactions: 'Нет транзакций',
    // Settings
    settings_title: 'Настройки',
    settings_language: 'Язык интерфейса',
    settings_legal_form: 'Правовая форма',
    settings_company_name: 'Название компании',
    settings_llm_model: 'Модель AI',
    settings_legal_ood: 'ООД (LLC)',
    settings_legal_et: 'ЕТ (ИП)',
    settings_legal_self: 'Самоосигуряващ се',
    settings_save: 'Сохранить',
    settings_saved: 'Сохранено ✓',
    settings_llm_provider: 'LLM провайдер',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Оригинальный API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'Модель LLM',
    settings_llm_load_models: 'Загрузить модели',
    settings_llm_test: 'Тест ответа и скорости',
    settings_llm_price_prompt: 'Цена input',
    settings_llm_price_completion: 'Цена output',
    settings_llm_context: 'Контекст',
    settings_llm_vendor: 'Вендор',
    settings_llm_latency: 'Скорость',
    settings_llm_test_result: 'Результат теста',
    settings_llm_models_hint: 'Список моделей загружается из базы OpenRouter',
    settings_llm_use_for_chat: 'Использовать выбранную модель в чате',
    // Common
    bgn: '€',
    loading: 'Загрузка...',
    error: 'Ошибка',
    common_send: 'Отправить',
  },
  uk: {
    nav_dashboard: 'Дашборд',
    nav_calculator: 'Податковий калькулятор',
    nav_salary: 'Зарплатний калькулятор',
    nav_employees: 'Співробітники / Зразок 1',
    nav_accounting: 'Бухгалтерія',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Звіти та декларації',
    nav_assistant: 'AI Асистент',
    nav_settings: 'Налаштування',
    dashboard_title: 'Дашборд',
    dashboard_next_deadline: 'Найближчий дедлайн',
    dashboard_legal_form: 'Правова форма',
    dashboard_no_deadlines: 'Немає майбутніх дедлайнів',
    calc_title: 'Податковий калькулятор',
    calc_income: 'Дохід (€)',
    calc_taxable: 'Оподатковувана база',
    calc_tax: 'Податок',
    calc_net: 'Чистий прибуток',
    salary_title: 'Зарплатний калькулятор',
    salary_gross: 'Брутто (€)',
    salary_employee_contrib: 'Внески працівника',
    salary_employer_contrib: 'Внески роботодавця',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нетто (€)',
    salary_total_cost: 'Загальні витрати роботодавця',
    accounting_title: 'Бухгалтерія',
    accounting_add: 'Додати транзакцію',
    accounting_description: 'Опис',
    accounting_amount: 'Сума (€)',
    accounting_no_transactions: 'Немає транзакцій',
    settings_title: 'Налаштування',
    settings_language: 'Мова інтерфейсу',
    settings_legal_form: 'Правова форма',
    settings_company_name: 'Назва компанії',
    settings_llm_model: 'Модель AI',
    settings_legal_ood: 'ООД (LLC)',
    settings_legal_et: 'ЕТ (ФОП)',
    settings_legal_self: 'Самозайнятий',
    settings_save: 'Зберегти',
    settings_saved: 'Збережено ✓',
    settings_llm_provider: 'LLM провайдер',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Original API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'LLM model',
    settings_llm_load_models: 'Load models',
    settings_llm_test: 'Response and speed test',
    settings_llm_price_prompt: 'Input price',
    settings_llm_price_completion: 'Output price',
    settings_llm_context: 'Context',
    settings_llm_vendor: 'Vendor',
    settings_llm_latency: 'Latency',
    settings_llm_test_result: 'Test result',
    settings_llm_models_hint: 'Models are loaded from OpenRouter catalog',
    settings_llm_use_for_chat: 'Use selected model in chat',
    bgn: '€',
    loading: 'Завантаження...',
    error: 'Помилка',
    common_send: 'Надіслати',
  },
  en: {
    nav_dashboard: 'Dashboard',
    nav_calculator: 'Tax Calculator',
    nav_salary: 'Salary Calculator',
    nav_employees: 'Employees / Form 1',
    nav_accounting: 'Accounting',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Reports & Declarations',
    nav_assistant: 'AI Assistant',
    nav_settings: 'Settings',
    dashboard_title: 'Dashboard',
    dashboard_next_deadline: 'Next Deadline',
    dashboard_legal_form: 'Legal Form',
    dashboard_no_deadlines: 'No upcoming deadlines',
    calc_title: 'Tax Calculator',
    calc_income: 'Income (€)',
    calc_taxable: 'Taxable base',
    calc_tax: 'Tax',
    calc_net: 'Net profit',
    salary_title: 'Salary Calculator',
    salary_gross: 'Gross (€)',
    salary_employee_contrib: 'Employee contributions',
    salary_employer_contrib: 'Employer contributions',
    salary_income_tax: 'Income tax',
    salary_net: 'Net (€)',
    salary_total_cost: 'Total employer cost',
    accounting_title: 'Accounting',
    accounting_add: 'Add transaction',
    accounting_description: 'Description',
    accounting_amount: 'Amount (€)',
    accounting_no_transactions: 'No transactions yet',
    settings_title: 'Settings',
    settings_language: 'Interface language',
    settings_legal_form: 'Legal form',
    settings_company_name: 'Company name',
    settings_llm_model: 'AI Model',
    settings_legal_ood: 'OOD (LLC)',
    settings_legal_et: 'ET (Sole trader)',
    settings_legal_self: 'Self-employed',
    settings_save: 'Save',
    settings_saved: 'Saved ✓',
    settings_llm_provider: 'LLM provider',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Original API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'LLM model',
    settings_llm_load_models: 'Load models',
    settings_llm_test: 'Response and speed test',
    settings_llm_price_prompt: 'Input price',
    settings_llm_price_completion: 'Output price',
    settings_llm_context: 'Context',
    settings_llm_vendor: 'Vendor',
    settings_llm_latency: 'Latency',
    settings_llm_test_result: 'Test result',
    settings_llm_models_hint: 'Models are loaded from OpenRouter catalog',
    settings_llm_use_for_chat: 'Use selected model in chat',
    bgn: '€',
    loading: 'Loading...',
    error: 'Error',
    common_send: 'Send',
  },
  bg: {
    nav_dashboard: 'Табло',
    nav_calculator: 'Данъчен калкулатор',
    nav_salary: 'Заплатен калкулатор',
    nav_employees: 'Служители / Образец 1',
    nav_accounting: 'Счетоводство',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Отчети и декларации',
    nav_assistant: 'AI Асистент',
    nav_settings: 'Настройки',
    dashboard_title: 'Табло',
    dashboard_next_deadline: 'Следващ краен срок',
    dashboard_legal_form: 'Правна форма',
    dashboard_no_deadlines: 'Няма предстоящи срокове',
    calc_title: 'Данъчен калкулатор',
    calc_income: 'Доход (€)',
    calc_taxable: 'Данъчна основа',
    calc_tax: 'Данък',
    calc_net: 'Нетна печалба',
    salary_title: 'Заплатен калкулатор',
    salary_gross: 'Бруто (€)',
    salary_employee_contrib: 'Осигуровки работник',
    salary_employer_contrib: 'Осигуровки работодател',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нето (€)',
    salary_total_cost: 'Общ разход работодател (€)',
    accounting_title: 'Счетоводство',
    accounting_add: 'Добави транзакция',
    accounting_description: 'Описание',
    accounting_amount: 'Сума (€)',
    accounting_no_transactions: 'Няма транзакции',
    settings_title: 'Настройки',
    settings_language: 'Език на интерфейса',
    settings_legal_form: 'Правна форма',
    settings_company_name: 'Наименование',
    settings_llm_model: 'AI Модел',
    settings_legal_ood: 'ООД',
    settings_legal_et: 'ЕТ',
    settings_legal_self: 'Самоосигуряващ се',
    settings_save: 'Запази',
    settings_saved: 'Запазено ✓',
    settings_llm_provider: 'LLM доставчик',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Оригинален API',
    settings_llm_api_key: 'API ключ',
    settings_llm_model_select: 'LLM модел',
    settings_llm_load_models: 'Зареди модели',
    settings_llm_test: 'Тест на отговор и скорост',
    settings_llm_price_prompt: 'Цена input',
    settings_llm_price_completion: 'Цена output',
    settings_llm_context: 'Контекст',
    settings_llm_vendor: 'Доставчик',
    settings_llm_latency: 'Скорост',
    settings_llm_test_result: 'Резултат от тест',
    settings_llm_models_hint: 'Моделите се зареждат от OpenRouter каталога',
    settings_llm_use_for_chat: 'Използвай избрания модел в чата',
    bgn: '€',
    loading: 'Зареждане...',
    error: 'Грешка',
    common_send: 'Изпрати',
  },
} as const

export function useT() {
  const language = useUserStore((s) => s.language)
  const t = (key: TranslationKey): string => {
    return (translations[language] as Record<string, string>)[key]
      ?? (translations.ru as Record<string, string>)[key]
      ?? key
  }
  return t
}
