import { useUserStore } from '../store/userStore'

export type TranslationKey = keyof typeof translations.ru

const translations = {
  ru: {
    // Nav
    nav_dashboard: 'Дашборд',
    nav_calendar: 'Данъчен календар',
    nav_auditor: 'Аудитор',
    nav_legal: 'Справочник законов',
    nav_calculator: 'Налоговый калькулятор',
    nav_salary: 'Зарплатный калькулятор',
    nav_employees: 'Служители / Образец 1',
    nav_accounting: 'Бухгалтерия',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Отчёты и декларации',
    nav_assistant: 'AI Ассистент',
    nav_settings: 'Настройки',
    nav_companies: 'Компании и группа',
    nav_learning:   'Обучение и тест',
    nav_lifecycle:  'Жизненный цикл',
    nav_expat:      'Жизнь в Болгарии',
    nav_audit_help: 'Проверка НАП',
    nav_vault: 'Архив документов',
    // Dashboard
    dashboard_title: 'Дашборд',
    dashboard_next_deadline: 'Ближайший дедлайн',
    dashboard_legal_form: 'Правовая форма',
    dashboard_no_deadlines: 'Нет предстоящих обязательств',
    // Calculator
    calc_title: 'Налоговый калькулятор',
    calc_income: 'Доход (€)',
    calc_taxable: 'Налогооблагаемая база',
    calc_tax: 'Налог',
    calc_net: 'Чистая прибыль',
    // Salary
    salary_title: 'Зарплатный калькулятор',
    salary_gross: 'Брутто (€)',
    salary_employee_contrib: 'Осигуровки работник',
    salary_employer_contrib: 'Осигуровки работодател',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нетто (€)',
    salary_total_cost: 'Общ разход работодател (€)',
    // Accounting
    accounting_title: 'Бухгалтерия',
    accounting_add: 'Добавить транзакцию',
    accounting_description: 'Описание',
    accounting_amount: 'Сумма (€)',
    accounting_no_transactions: 'Нет транзакций',
    // Settings
    settings_title: 'Настройки',
    settings_language: 'Язык интерфейса',
    settings_legal_form: 'Правовая форма',
    settings_company_name: 'Название компании',
    settings_llm_model: 'Модель AI',
    settings_legal_ood: 'ООД (LLC)',
    settings_legal_et: 'ЕТ (ИП)',
    settings_legal_self: 'Самоосигуряващ се',
    settings_save: 'Сохранить',
    settings_saved: 'Сохранено ✓',
    settings_llm_provider: 'LLM провайдер',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Оригинальный API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'Модель LLM',
    settings_llm_load_models: 'Загрузить модели',
    settings_llm_test: 'Тест ответа и скорости',
    settings_llm_price_prompt: 'Цена input',
    settings_llm_price_completion: 'Цена output',
    settings_llm_context: 'Контекст',
    settings_llm_vendor: 'Вендор',
    settings_llm_latency: 'Скорость',
    settings_llm_test_result: 'Результат теста',
    settings_llm_models_hint: 'Список моделей загружается из базы OpenRouter',
    settings_llm_use_for_chat: 'Использовать выбранную модель в чате',
    // Common
    bgn: '€',
    loading: 'Загрузка...',
    error: 'Ошибка',
    common_send: 'Отправить',

    // Group labels in sidebar
    group_main: 'ГЛАВНОЕ',
    group_accounting: 'БУХГАЛТЕРИЯ',
    group_taxes: 'НАЛОГИ И ФИНАНСЫ',
    group_employees: 'СОТРУДНИКИ',
    group_deadlines: 'СРОКИ И КОНТРОЛЬ',
    group_knowledge: 'ЗНАНИЯ',
    group_system: 'СИСТЕМА',

    // Page titles
    page_dashboard: 'Обзор',
    page_auditor: 'Аудитор',
    page_accounting: 'Счетоводство',
    page_calendar: 'Данъчен календар',
    page_legal: 'Справочник законов',
    page_reports: 'Отчёты и декларации',
    page_settings: 'Настройки',
    page_employees: 'Служители и Образец 1',
    page_platforms: 'App Store / Google Play',
    page_assistant: 'AI Ассистент',
    page_salary: 'Зарплатный калькулятор',
    page_calculator: 'Налоговый калькулятор',

    // Accounting tabs
    tab_income: 'Доходи',
    tab_expense: 'Разходи',
    tab_ledger: 'Главна книга',
    tab_opr: 'ОПР',
    tab_balance: 'Баланс',
    tab_reports_nap: 'Справки НАП',
    tab_documents: 'Документи',

    // Settings tabs
    tab_profile: 'Профил',
    tab_ai: 'AI модел',
    tab_integrations: 'Интеграции',
    tab_system: 'Система',

    // Common UI buttons
    btn_save: 'Сохранить',
    btn_saved: 'Сохранено ✓',
    btn_add: 'Добавить',
    btn_cancel: 'Отмена',
    btn_download: 'Скачать',
    btn_send: 'Отправить',
    btn_check: 'Проверить',
    btn_generate: 'Генерировать',
    btn_close: 'Закрыть',
    btn_back: '← Назад',
    btn_next: 'Вперёд →',

    // Common labels
    label_period: 'Период',
    label_company: 'Компания',
    label_amount: 'Сумма (€)',
    label_date: 'Дата',
    label_description: 'Описание',
    label_type: 'Тип',
    label_status: 'Статус',
    label_total: 'Итого',
    label_income: 'Приходи',
    label_expense: 'Разходи',
    label_result: 'Резултат',
    label_month: 'Месяц',
    label_year: 'Год',
    label_now: 'Сейчас',
    label_from: 'От',
    label_to: 'До',
    label_name: 'Название',
    label_language: 'Язык интерфейса',
    label_legal_form: 'Правовая форма',

    // Auditor
    auditor_health: 'Индекс здоровья',
    auditor_critical: 'Критических',
    auditor_high: 'Высоких',
    auditor_total: 'Всего',
    auditor_recommendation: 'Рекомендация',
    auditor_push_title: 'Push-уведомления о дедлайнах',
    auditor_enable_push: 'Включить уведомления',
    auditor_no_risks: 'Рисков не обнаружено',

    // Calendar
    calendar_upcoming: 'Ближайшие 30 дней',
    calendar_overdue: 'Просроченные обязательства',
    calendar_this_month: 'Этот месяц',
    calendar_next_month: 'Следующий',
    calendar_full_year: 'Весь год',
    calendar_check_legislation: 'Проверить законодательство',
    calendar_subtitle: 'Отчётность и уплата налогов · сроки и штрафы · ставки 2026',

    // Dashboard extended
    dashboard_rates_title: 'Ключевые ставки 2026',
    dashboard_upcoming: 'Предстоящие срокове · 14 дней',

    // Employees
    employees_subtitle: 'Управление сотрудниками · ежемесячная форма до 25-го числа',
    employees_add: '+ Добавить сотрудника',
    employees_no_employees: 'Нет сотрудников. Добавьте первого.',
    employees_active: 'Активен',
    employees_inactive: 'Неактивен',

    // Onboarding
    onboarding_welcome_title: 'TaxBG Pro',
    onboarding_welcome_subtitle: 'Помогаем IT предпринимателям вести учёт в Болгарии самостоятельно — без бухгалтера, на русском языке.',
    onboarding_start: 'Начать настройку →',
    onboarding_legal_form_title: 'Правовая форма',
    onboarding_company_title: 'Данные компании',
    onboarding_vat_title: 'ДДС и сотрудники',
    onboarding_done_title: 'Всё готово!',
    onboarding_enter: 'Войти в приложение 🌹',

    // Legal reference
    legal_today_tab: 'Сегодня актуально',
    legal_all_tab: 'Все законы',
    legal_search_placeholder: 'Поиск: ЗКПО, дивиденти, амортизация...',
    legal_subtitle: 'Действующие законы Болгарии 2026 · нажмите ? для AI-объяснения на вашем языке',

    // Integrations
    integrations_nap_title: 'НАП API (НАПИ)',
    integrations_nap_desc: 'Автоматическая подача деклараций прямо из приложения',
    integrations_email_title: 'Email отправка',
    integrations_pik_title: 'ПИК код НАП',
    integrations_connected: '● Подключён',
    integrations_not_connected: '○ Не подключён',

    // Settings system tab
    system_reset_onboarding: 'Повторить онбординг',
    system_data_info: 'Все данные хранятся локально в браузере',

    // Help popover
    help_disclaimer: 'TaxBG AI · данные 2026 · не является юридической консультацией',
  },
  uk: {
    nav_dashboard: 'Дашборд',
    nav_calendar: 'Податковий календар',
    nav_auditor: 'Аудитор',
    nav_legal: 'Довідник законів',
    nav_calculator: 'Податковий калькулятор',
    nav_salary: 'Зарплатний калькулятор',
    nav_employees: 'Співробітники / Зразок 1',
    nav_accounting: 'Бухгалтерія',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Звіти та декларації',
    nav_assistant: 'AI Асистент',
    nav_settings: 'Налаштування',
    nav_companies: 'Компанії та група',
    nav_learning:  'Навчання і тест',
    nav_lifecycle: 'Життєвий цикл',
    nav_expat:     'Життя в Болгарії',
    nav_audit_help: 'Перевірка НАП',
    nav_vault: 'Архів документів',
    dashboard_title: 'Дашборд',
    dashboard_next_deadline: 'Найближчий дедлайн',
    dashboard_legal_form: 'Правова форма',
    dashboard_no_deadlines: 'Немає майбутніх зобов\'язань',
    calc_title: 'Податковий калькулятор',
    calc_income: 'Дохід (€)',
    calc_taxable: 'Оподатковувана база',
    calc_tax: 'Податок',
    calc_net: 'Чистий прибуток',
    salary_title: 'Зарплатний калькулятор',
    salary_gross: 'Брутто (€)',
    salary_employee_contrib: 'Внески працівника',
    salary_employer_contrib: 'Внески роботодавця',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нетто (€)',
    salary_total_cost: 'Загальні витрати роботодавця',
    accounting_title: 'Бухгалтерія',
    accounting_add: 'Додати транзакцію',
    accounting_description: 'Опис',
    accounting_amount: 'Сума (€)',
    accounting_no_transactions: 'Немає транзакцій',
    settings_title: 'Налаштування',
    settings_language: 'Мова інтерфейсу',
    settings_legal_form: 'Правова форма',
    settings_company_name: 'Назва компанії',
    settings_llm_model: 'Модель AI',
    settings_legal_ood: 'ООД (LLC)',
    settings_legal_et: 'ЕТ (ФОП)',
    settings_legal_self: 'Самозайнятий',
    settings_save: 'Зберегти',
    settings_saved: 'Збережено ✓',
    settings_llm_provider: 'LLM провайдер',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Original API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'LLM model',
    settings_llm_load_models: 'Load models',
    settings_llm_test: 'Response and speed test',
    settings_llm_price_prompt: 'Input price',
    settings_llm_price_completion: 'Output price',
    settings_llm_context: 'Context',
    settings_llm_vendor: 'Vendor',
    settings_llm_latency: 'Latency',
    settings_llm_test_result: 'Test result',
    settings_llm_models_hint: 'Models are loaded from OpenRouter catalog',
    settings_llm_use_for_chat: 'Use selected model in chat',
    bgn: '€',
    loading: 'Завантаження...',
    error: 'Помилка',
    common_send: 'Надіслати',

    group_main: 'ГОЛОВНЕ',
    group_accounting: 'БУХГАЛТЕРІЯ',
    group_taxes: 'ПОДАТКИ І ФІНАНСИ',
    group_employees: 'СПІВРОБІТНИКИ',
    group_deadlines: 'ТЕРМІНИ І КОНТРОЛЬ',
    group_knowledge: 'ЗНАННЯ',
    group_system: 'СИСТЕМА',

    page_dashboard: 'Огляд',
    page_auditor: 'Аудитор',
    page_accounting: 'Бухгалтерія',
    page_calendar: 'Податковий календар',
    page_legal: 'Довідник законів',
    page_reports: 'Звіти та декларації',
    page_settings: 'Налаштування',
    page_employees: 'Співробітники та Зразок 1',
    page_platforms: 'App Store / Google Play',
    page_assistant: 'AI Асистент',
    page_salary: 'Зарплатний калькулятор',
    page_calculator: 'Податковий калькулятор',

    tab_income: 'Доходи',
    tab_expense: 'Витрати',
    tab_ledger: 'Головна книга',
    tab_opr: 'ОПД',
    tab_balance: 'Баланс',
    tab_reports_nap: 'Довідки НАП',
    tab_documents: 'Документи',

    tab_profile: 'Профіль',
    tab_ai: 'AI модель',
    tab_integrations: 'Інтеграції',
    tab_system: 'Система',

    btn_save: 'Зберегти',
    btn_saved: 'Збережено ✓',
    btn_add: 'Додати',
    btn_cancel: 'Скасувати',
    btn_download: 'Завантажити',
    btn_send: 'Надіслати',
    btn_check: 'Перевірити',
    btn_generate: 'Генерувати',
    btn_close: 'Закрити',
    btn_back: '← Назад',
    btn_next: 'Вперед →',

    label_period: 'Період',
    label_company: 'Компанія',
    label_amount: 'Сума (€)',
    label_date: 'Дата',
    label_description: 'Опис',
    label_type: 'Тип',
    label_status: 'Статус',
    label_total: 'Разом',
    label_income: 'Доходи',
    label_expense: 'Витрати',
    label_result: 'Результат',
    label_month: 'Місяць',
    label_year: 'Рік',
    label_now: 'Зараз',
    label_from: 'Від',
    label_to: 'До',
    label_name: 'Назва',
    label_language: 'Мова інтерфейсу',
    label_legal_form: 'Правова форма',

    auditor_health: 'Індекс здоров\'я',
    auditor_critical: 'Критичних',
    auditor_high: 'Високих',
    auditor_total: 'Всього',
    auditor_recommendation: 'Рекомендація',
    auditor_push_title: 'Push-сповіщення про дедлайни',
    auditor_enable_push: 'Увімкнути сповіщення',
    auditor_no_risks: 'Ризиків не виявлено',

    calendar_upcoming: 'Найближчі 30 днів',
    calendar_overdue: 'Прострочені зобов\'язання',
    calendar_this_month: 'Цей місяць',
    calendar_next_month: 'Наступний',
    calendar_full_year: 'Весь рік',
    calendar_check_legislation: 'Перевірити законодавство',
    calendar_subtitle: 'Звітність і сплата податків · терміни і штрафи · ставки 2026',

    dashboard_rates_title: 'Ключові ставки 2026',
    dashboard_upcoming: 'Майбутні терміни · 14 днів',

    employees_subtitle: 'Управління співробітниками · щомісячна форма до 25-го числа',
    employees_add: '+ Додати співробітника',
    employees_no_employees: 'Немає співробітників. Додайте першого.',
    employees_active: 'Активний',
    employees_inactive: 'Неактивний',

    onboarding_welcome_title: 'TaxBG Pro',
    onboarding_welcome_subtitle: 'Допомагаємо IT підприємцям вести облік у Болгарії самостійно — без бухгалтера, на вашій мові.',
    onboarding_start: 'Розпочати налаштування →',
    onboarding_legal_form_title: 'Правова форма',
    onboarding_company_title: 'Дані компанії',
    onboarding_vat_title: 'ПДВ і співробітники',
    onboarding_done_title: 'Все готово!',
    onboarding_enter: 'Увійти в додаток 🌹',

    legal_today_tab: 'Сьогодні актуально',
    legal_all_tab: 'Всі закони',
    legal_search_placeholder: 'Пошук: ЗКПО, дивіденди, амортизація...',
    legal_subtitle: 'Чинні закони Болгарії 2026 · натисніть ? для AI-пояснення вашою мовою',

    integrations_nap_title: 'НАП API (НАПИ)',
    integrations_nap_desc: 'Автоматична подача декларацій прямо з додатку',
    integrations_email_title: 'Email відправка',
    integrations_pik_title: 'ПІК код НАП',
    integrations_connected: '● Підключено',
    integrations_not_connected: '○ Не підключено',

    system_reset_onboarding: 'Повторити онбординг',
    system_data_info: 'Всі дані зберігаються локально в браузері',

    help_disclaimer: 'TaxBG AI · дані 2026 · не є юридичною консультацією',
  },
  en: {
    nav_dashboard: 'Dashboard',
    nav_calendar: 'Tax Calendar',
    nav_auditor: 'Auditor',
    nav_legal: 'Legal Reference',
    nav_calculator: 'Tax Calculator',
    nav_salary: 'Salary Calculator',
    nav_employees: 'Employees / Form 1',
    nav_accounting: 'Accounting',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Reports & Declarations',
    nav_assistant: 'AI Assistant',
    nav_settings: 'Settings',
    nav_companies: 'Companies & Group',
    nav_learning:  'Learning & Testing',
    nav_lifecycle: 'Company Lifecycle',
    nav_expat:     'Life in Bulgaria',
    nav_audit_help: 'Tax Audit Help',
    nav_vault: 'Document Vault',
    dashboard_title: 'Dashboard',
    dashboard_next_deadline: 'Next Deadline',
    dashboard_legal_form: 'Legal Form',
    dashboard_no_deadlines: 'No upcoming obligations',
    calc_title: 'Tax Calculator',
    calc_income: 'Income (€)',
    calc_taxable: 'Taxable base',
    calc_tax: 'Tax',
    calc_net: 'Net profit',
    salary_title: 'Salary Calculator',
    salary_gross: 'Gross (€)',
    salary_employee_contrib: 'Employee contributions',
    salary_employer_contrib: 'Employer contributions',
    salary_income_tax: 'Income tax',
    salary_net: 'Net (€)',
    salary_total_cost: 'Total employer cost',
    accounting_title: 'Accounting',
    accounting_add: 'Add transaction',
    accounting_description: 'Description',
    accounting_amount: 'Amount (€)',
    accounting_no_transactions: 'No transactions yet',
    settings_title: 'Settings',
    settings_language: 'Interface language',
    settings_legal_form: 'Legal form',
    settings_company_name: 'Company name',
    settings_llm_model: 'AI Model',
    settings_legal_ood: 'OOD (LLC)',
    settings_legal_et: 'ET (Sole trader)',
    settings_legal_self: 'Self-employed',
    settings_save: 'Save',
    settings_saved: 'Saved ✓',
    settings_llm_provider: 'LLM provider',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Original API',
    settings_llm_api_key: 'API key',
    settings_llm_model_select: 'LLM model',
    settings_llm_load_models: 'Load models',
    settings_llm_test: 'Response and speed test',
    settings_llm_price_prompt: 'Input price',
    settings_llm_price_completion: 'Output price',
    settings_llm_context: 'Context',
    settings_llm_vendor: 'Vendor',
    settings_llm_latency: 'Latency',
    settings_llm_test_result: 'Test result',
    settings_llm_models_hint: 'Models are loaded from OpenRouter catalog',
    settings_llm_use_for_chat: 'Use selected model in chat',
    bgn: '€',
    loading: 'Loading...',
    error: 'Error',
    common_send: 'Send',

    group_main: 'MAIN',
    group_accounting: 'ACCOUNTING',
    group_taxes: 'TAXES & FINANCE',
    group_employees: 'EMPLOYEES',
    group_deadlines: 'DEADLINES',
    group_knowledge: 'KNOWLEDGE',
    group_system: 'SYSTEM',

    page_dashboard: 'Overview',
    page_auditor: 'Auditor',
    page_accounting: 'Accounting',
    page_calendar: 'Tax Calendar',
    page_legal: 'Legal Reference',
    page_reports: 'Reports & Declarations',
    page_settings: 'Settings',
    page_employees: 'Employees & Form 1',
    page_platforms: 'App Store / Google Play',
    page_assistant: 'AI Assistant',
    page_salary: 'Salary Calculator',
    page_calculator: 'Tax Calculator',

    tab_income: 'Income',
    tab_expense: 'Expenses',
    tab_ledger: 'General Ledger',
    tab_opr: 'P&L',
    tab_balance: 'Balance Sheet',
    tab_reports_nap: 'NAP Reports',
    tab_documents: 'Documents',

    tab_profile: 'Profile',
    tab_ai: 'AI Model',
    tab_integrations: 'Integrations',
    tab_system: 'System',

    btn_save: 'Save',
    btn_saved: 'Saved ✓',
    btn_add: 'Add',
    btn_cancel: 'Cancel',
    btn_download: 'Download',
    btn_send: 'Send',
    btn_check: 'Check',
    btn_generate: 'Generate',
    btn_close: 'Close',
    btn_back: '← Back',
    btn_next: 'Next →',

    label_period: 'Period',
    label_company: 'Company',
    label_amount: 'Amount (€)',
    label_date: 'Date',
    label_description: 'Description',
    label_type: 'Type',
    label_status: 'Status',
    label_total: 'Total',
    label_income: 'Income',
    label_expense: 'Expenses',
    label_result: 'Result',
    label_month: 'Month',
    label_year: 'Year',
    label_now: 'Now',
    label_from: 'From',
    label_to: 'To',
    label_name: 'Name',
    label_language: 'Interface language',
    label_legal_form: 'Legal form',

    auditor_health: 'Health Score',
    auditor_critical: 'Critical',
    auditor_high: 'High',
    auditor_total: 'Total',
    auditor_recommendation: 'Recommendation',
    auditor_push_title: 'Deadline push notifications',
    auditor_enable_push: 'Enable notifications',
    auditor_no_risks: 'No risks detected',

    calendar_upcoming: 'Next 30 days',
    calendar_overdue: 'Overdue obligations',
    calendar_this_month: 'This month',
    calendar_next_month: 'Next month',
    calendar_full_year: 'Full year',
    calendar_check_legislation: 'Check legislation',
    calendar_subtitle: 'Reporting and tax payments · deadlines and penalties · 2026 rates',

    dashboard_rates_title: 'Key rates 2026',
    dashboard_upcoming: 'Upcoming deadlines · 14 days',

    employees_subtitle: 'Employee management · monthly form by 25th',
    employees_add: '+ Add employee',
    employees_no_employees: 'No employees. Add the first one.',
    employees_active: 'Active',
    employees_inactive: 'Inactive',

    onboarding_welcome_title: 'TaxBG Pro',
    onboarding_welcome_subtitle: 'We help IT entrepreneurs manage accounting in Bulgaria independently — no accountant needed.',
    onboarding_start: 'Start setup →',
    onboarding_legal_form_title: 'Legal form',
    onboarding_company_title: 'Company details',
    onboarding_vat_title: 'VAT and employees',
    onboarding_done_title: 'All done!',
    onboarding_enter: 'Enter the app 🌹',

    legal_today_tab: 'Today relevant',
    legal_all_tab: 'All laws',
    legal_search_placeholder: 'Search: ZKPO, dividends, depreciation...',
    legal_subtitle: 'Bulgarian laws 2026 · press ? for AI explanation in your language',

    integrations_nap_title: 'NAP API (NAPI)',
    integrations_nap_desc: 'Automatic declaration submission directly from the app',
    integrations_email_title: 'Email sending',
    integrations_pik_title: 'NAP PIN code',
    integrations_connected: '● Connected',
    integrations_not_connected: '○ Not connected',

    system_reset_onboarding: 'Repeat onboarding',
    system_data_info: 'All data is stored locally in your browser',

    help_disclaimer: 'TaxBG AI · 2026 data · not legal advice',
  },
  bg: {
    nav_dashboard: 'Табло',
    nav_calendar: 'Данъчен календар',
    nav_auditor: 'Одитор',
    nav_legal: 'Наръчник на законите',
    nav_calculator: 'Данъчен калкулатор',
    nav_salary: 'Заплатен калкулатор',
    nav_employees: 'Служители / Образец 1',
    nav_accounting: 'Счетоводство',
    nav_platforms: 'App Store / Google Play',
    nav_reports: 'Отчети и декларации',
    nav_assistant: 'AI Асистент',
    nav_settings: 'Настройки',
    nav_companies: 'Компании и група',
    nav_learning:  'Обучение и тест',
    nav_lifecycle: 'Жизнен цикъл',
    nav_expat:     'Живот в България',
    nav_audit_help: 'Ревизия НАП',
    nav_vault: 'Архив на документи',
    dashboard_title: 'Табло',
    dashboard_next_deadline: 'Следващ краен срок',
    dashboard_legal_form: 'Правна форма',
    dashboard_no_deadlines: 'Няма предстоящи задължения',
    calc_title: 'Данъчен калкулатор',
    calc_income: 'Доход (€)',
    calc_taxable: 'Данъчна основа',
    calc_tax: 'Данък',
    calc_net: 'Нетна печалба',
    salary_title: 'Заплатен калкулатор',
    salary_gross: 'Бруто (€)',
    salary_employee_contrib: 'Осигуровки работник',
    salary_employer_contrib: 'Осигуровки работодател',
    salary_income_tax: 'ДДФЛ',
    salary_net: 'Нето (€)',
    salary_total_cost: 'Общ разход работодател (€)',
    accounting_title: 'Счетоводство',
    accounting_add: 'Добави транзакция',
    accounting_description: 'Описание',
    accounting_amount: 'Сума (€)',
    accounting_no_transactions: 'Няма транзакции',
    settings_title: 'Настройки',
    settings_language: 'Език на интерфейса',
    settings_legal_form: 'Правна форма',
    settings_company_name: 'Наименование',
    settings_llm_model: 'AI Модел',
    settings_legal_ood: 'ООД',
    settings_legal_et: 'ЕТ',
    settings_legal_self: 'Самоосигуряващ се',
    settings_save: 'Запази',
    settings_saved: 'Запазено ✓',
    settings_llm_provider: 'LLM доставчик',
    settings_provider_openrouter: 'OpenRouter',
    settings_provider_original: 'Оригинален API',
    settings_llm_api_key: 'API ключ',
    settings_llm_model_select: 'LLM модел',
    settings_llm_load_models: 'Зареди модели',
    settings_llm_test: 'Тест на отговор и скорост',
    settings_llm_price_prompt: 'Цена input',
    settings_llm_price_completion: 'Цена output',
    settings_llm_context: 'Контекст',
    settings_llm_vendor: 'Доставчик',
    settings_llm_latency: 'Скорост',
    settings_llm_test_result: 'Резултат от тест',
    settings_llm_models_hint: 'Моделите се зареждат от OpenRouter каталога',
    settings_llm_use_for_chat: 'Използвай избрания модел в чата',
    bgn: '€',
    loading: 'Зареждане...',
    error: 'Грешка',
    common_send: 'Изпрати',

    group_main: 'ГЛАВНО',
    group_accounting: 'СЧЕТОВОДСТВО',
    group_taxes: 'ДАНЪЦИ И ФИНАНСИ',
    group_employees: 'СЛУЖИТЕЛИ',
    group_deadlines: 'СРОКОВЕ И КОНТРОЛ',
    group_knowledge: 'ЗНАНИЯ',
    group_system: 'СИСТЕМА',

    page_dashboard: 'Табло',
    page_auditor: 'Одитор',
    page_accounting: 'Счетоводство',
    page_calendar: 'Данъчен календар',
    page_legal: 'Наръчник на законите',
    page_reports: 'Отчети и декларации',
    page_settings: 'Настройки',
    page_employees: 'Служители и Образец 1',
    page_platforms: 'App Store / Google Play',
    page_assistant: 'AI Асистент',
    page_salary: 'Заплатен калкулатор',
    page_calculator: 'Данъчен калкулатор',

    tab_income: 'Доходи',
    tab_expense: 'Разходи',
    tab_ledger: 'Главна книга',
    tab_opr: 'ОПР',
    tab_balance: 'Баланс',
    tab_reports_nap: 'Справки НАП',
    tab_documents: 'Документи',

    tab_profile: 'Профил',
    tab_ai: 'AI модел',
    tab_integrations: 'Интеграции',
    tab_system: 'Система',

    btn_save: 'Запази',
    btn_saved: 'Запазено ✓',
    btn_add: 'Добави',
    btn_cancel: 'Отказ',
    btn_download: 'Изтегли',
    btn_send: 'Изпрати',
    btn_check: 'Провери',
    btn_generate: 'Генерирай',
    btn_close: 'Затвори',
    btn_back: '← Назад',
    btn_next: 'Напред →',

    label_period: 'Период',
    label_company: 'Компания',
    label_amount: 'Сума (€)',
    label_date: 'Дата',
    label_description: 'Описание',
    label_type: 'Тип',
    label_status: 'Статус',
    label_total: 'Общо',
    label_income: 'Приходи',
    label_expense: 'Разходи',
    label_result: 'Резултат',
    label_month: 'Месец',
    label_year: 'Година',
    label_now: 'Сега',
    label_from: 'От',
    label_to: 'До',
    label_name: 'Наименование',
    label_language: 'Език на интерфейса',
    label_legal_form: 'Правна форма',

    auditor_health: 'Индекс на здравето',
    auditor_critical: 'Критични',
    auditor_high: 'Високи',
    auditor_total: 'Общо',
    auditor_recommendation: 'Препоръка',
    auditor_push_title: 'Push известия за срокове',
    auditor_enable_push: 'Включи известия',
    auditor_no_risks: 'Няма открити рискове',

    calendar_upcoming: 'Следващи 30 дни',
    calendar_overdue: 'Просрочени задължения',
    calendar_this_month: 'Този месец',
    calendar_next_month: 'Следващ',
    calendar_full_year: 'Цялата година',
    calendar_check_legislation: 'Провери законодателството',
    calendar_subtitle: 'Отчетност и плащане на данъци · срокове и санкции · ставки 2026',

    dashboard_rates_title: 'Ключови ставки 2026',
    dashboard_upcoming: 'Предстоящи срокове · 14 дни',

    employees_subtitle: 'Управление на служители · месечна форма до 25-то число',
    employees_add: '+ Добави служител',
    employees_no_employees: 'Няма служители. Добавете първия.',
    employees_active: 'Активен',
    employees_inactive: 'Неактивен',

    onboarding_welcome_title: 'TaxBG Pro',
    onboarding_welcome_subtitle: 'Помагаме на IT предприемачи да водят счетоводство в България самостоятелно — без счетоводител.',
    onboarding_start: 'Започни настройката →',
    onboarding_legal_form_title: 'Правна форма',
    onboarding_company_title: 'Данни за фирмата',
    onboarding_vat_title: 'ДДС и служители',
    onboarding_done_title: 'Готово!',
    onboarding_enter: 'Влез в приложението 🌹',

    legal_today_tab: 'Днес актуално',
    legal_all_tab: 'Всички закони',
    legal_search_placeholder: 'Търсене: ЗКПО, дивиденти, амортизация...',
    legal_subtitle: 'Действащи закони на България 2026 · натиснете ? за AI обяснение на вашия език',

    integrations_nap_title: 'НАП API (НАПИ)',
    integrations_nap_desc: 'Автоматично подаване на декларации директно от приложението',
    integrations_email_title: 'Email изпращане',
    integrations_pik_title: 'ПИК код НАП',
    integrations_connected: '● Свързан',
    integrations_not_connected: '○ Не е свързан',

    system_reset_onboarding: 'Повтори онбординга',
    system_data_info: 'Всички данни се съхраняват локално в браузъра',

    help_disclaimer: 'TaxBG AI · данни 2026 · не е правна консултация',
  },
} as const

export function useT() {
  const language = useUserStore((s) => s.language)
  const t = (key: TranslationKey): string => {
    return (translations[language] as Record<string, string>)[key]
      ?? (translations.ru as Record<string, string>)[key]
      ?? key
  }
  return t
}
