import type { LegalForm } from '../store/userStore'

export type EventCategory =
  | 'vat'
  | 'corporate'
  | 'social'
  | 'statistical'
  | 'registry'
  | 'kep'
  | 'salary'
  | 'advance'
  | 'other'

export type EventRecurrence = 'monthly' | 'annual' | 'quarterly' | 'once'

export interface CalendarEvent {
  id: string
  title_ru: string
  title_bg: string
  description_ru: string
  authority: string
  category: EventCategory
  recurrence: EventRecurrence
  dayOfMonth?: number
  month?: number
  day?: number
  forms: LegalForm[]
  penaltyInfo_ru: string
  penaltyAmount?: string
  links: { label: string; url: string }[]
  // Legislation tracking
  legalBasis: string
  dv: string
  publishedAt: string
  effectiveFrom: string
  effectiveTo: string | null
  version: string
  lastVerified: string
}

export const CALENDAR_EVENTS_2026: CalendarEvent[] = [
  {
    id: 'dds-monthly',
    title_ru: 'Декларация по ДДС',
    title_bg: 'Справка-декларация по ЗДДС',
    description_ru: 'Ежемесячная декларация по НДС за предыдущий месяц. Дневники покупок и продаж. Подаётся онлайн через e-services.nap.bg с КЕП.',
    authority: 'НАП',
    category: 'vat',
    recurrence: 'monthly',
    dayOfMonth: 14,
    forms: ['ood', 'et'],
    penaltyInfo_ru: 'Штраф до 5 000 € за просрочку · лишение ДДС регистрации при повторном нарушении',
    penaltyAmount: 'до 5 000 €',
    links: [
      { label: 'e-services.nap.bg', url: 'https://e-services.nap.bg' },
      { label: 'ЗДДС чл. 125', url: 'https://nap.bg/page?id=392' },
    ],
    legalBasis: 'ЗДДС чл. 125',
    dv: 'ДВ бр. 104/2025',
    publishedAt: '2025-12-15',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'osig-employees-monthly',
    title_ru: 'Осигуровки за служители (Образец 1)',
    title_bg: 'Осигурителни вноски за служители',
    description_ru: 'Декларация Образец 1 и уплата осигуровок за всех сотрудников за предыдущий месяц.',
    authority: 'НАП',
    category: 'social',
    recurrence: 'monthly',
    dayOfMonth: 25,
    forms: ['ood', 'et'],
    penaltyInfo_ru: 'Пеня 0.03% в день от суммы задолженности',
    penaltyAmount: '0.03%/день',
    links: [{ label: 'inetdec.nra.bg', url: 'https://inetdec.nra.bg' }],
    legalBasis: 'КСО чл. 7',
    dv: 'ДВ бр. 104/2025',
    publishedAt: '2025-12-15',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'osig-self-monthly',
    title_ru: 'Осигуровки самоосигуряващ',
    title_bg: 'Осигурителни вноски самоосигуряващ се',
    description_ru: 'Ежемесячная уплата осигуровок за себя: ДОО + УПФ + ЗО (+ ОЗМ по избор).',
    authority: 'НАП',
    category: 'social',
    recurrence: 'monthly',
    dayOfMonth: 25,
    forms: ['self', 'et'],
    penaltyInfo_ru: 'Пеня 0.03% в день',
    penaltyAmount: '0.03%/день',
    links: [{ label: 'e-services.nap.bg', url: 'https://e-services.nap.bg' }],
    legalBasis: 'КСО чл. 6',
    dv: 'ДВ бр. 104/2025',
    publishedAt: '2025-12-15',
    effectiveFrom: '2026-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'salary-monthly',
    title_ru: 'Выплата зарплаты',
    title_bg: 'Изплащане на заплати',
    description_ru: 'Законодательно установленный срок выплаты зарплаты — не позднее последнего числа месяца, если иное не предусмотрено трудовым договором.',
    authority: 'НАП',
    category: 'salary',
    recurrence: 'monthly',
    dayOfMonth: 28,
    forms: ['ood', 'et'],
    penaltyInfo_ru: 'Административная ответственность по КТ · штраф 1 500–15 000 €',
    penaltyAmount: '1 500–15 000 €',
    links: [],
    legalBasis: 'КТ чл. 270',
    dv: 'ДВ бр. 26/1986',
    publishedAt: '1986-04-01',
    effectiveFrom: '1986-04-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },

  {
    id: 'kep-check-annual',
    title_ru: 'Проверка срока КЕП',
    title_bg: 'Проверка на срока на КЕП',
    description_ru: 'Проверьте срок действия квалифицированной электронной подписи. КЕП нужен для подачи всех онлайн-отчётов. Обновите заранее в B-Trust или Evrotrust.',
    authority: 'НАП',
    category: 'kep',
    recurrence: 'annual',
    month: 1,
    day: 15,
    forms: ['ood', 'et', 'self'],
    penaltyInfo_ru: 'Без КЕП невозможна электронная подача — косвенная просрочка всех деклараций',
    penaltyAmount: 'косвенно',
    links: [
      { label: 'B-Trust', url: 'https://btrust.bg' },
      { label: 'Evrotrust', url: 'https://evrotrust.com' },
    ],
    legalBasis: 'ЗЕДЕУУ чл. 24',
    dv: 'ДВ бр. 34/2001',
    publishedAt: '2001-04-11',
    effectiveFrom: '2001-04-11',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'spravka1-annual',
    title_ru: 'Справка 1 — доходы сотрудников за год',
    title_bg: 'Справка 1 — годишни доходи на служителите',
    description_ru: 'Годовая информационная справка о доходах каждого сотрудника. Подаётся в НАП до 28 февраля.',
    authority: 'НАП',
    category: 'social',
    recurrence: 'annual',
    month: 2,
    day: 28,
    forms: ['ood', 'et'],
    penaltyInfo_ru: 'Штраф 250–500 €',
    penaltyAmount: '250–500 €',
    links: [{ label: 'НАП', url: 'https://nap.bg' }],
    legalBasis: 'ЗДДФЛ чл. 73',
    dv: 'ДВ бр. 95/2006',
    publishedAt: '2006-11-24',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'nsi-annual',
    title_ru: 'Годовой отчёт в НСИ',
    title_bg: 'Годишен отчет в НСИ',
    description_ru: 'Статистический отчёт о деятельности предприятия за предыдущий год. Подаётся онлайн на nsi.bg с КЕП до 31 марта. Самый часто забываемый отчёт.',
    authority: 'НСИ',
    category: 'statistical',
    recurrence: 'annual',
    month: 3,
    day: 31,
    forms: ['ood', 'et'],
    penaltyInfo_ru: 'Штраф 500–2 000 € (ЗСТАТИСТИКАТА чл. 52)',
    penaltyAmount: '500–2 000 €',
    links: [{ label: 'nsi.bg', url: 'https://nsi.bg' }],
    legalBasis: 'ЗСТАТИСТИКАТА чл. 20',
    dv: 'ДВ бр. 57/1999',
    publishedAt: '1999-06-25',
    effectiveFrom: '1999-06-25',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'gdd-zddfl-annual',
    title_ru: 'Годовая декларация ЗДДФЛ (ЕТ/самоосиг.)',
    title_bg: 'Годишна данъчна декларация ЗДДФЛ',
    description_ru: 'Годовая налоговая декларация по ЗДДФЛ для ЕТ и самоосигуряващ. Срок — 30 апреля. При подаче до 31 марта онлайн — скидка 5% от налога (до 255.65 €).',
    authority: 'НАП',
    category: 'corporate',
    recurrence: 'annual',
    month: 4,
    day: 30,
    forms: ['et', 'self'],
    penaltyInfo_ru: 'Штраф 500–3 000 €',
    penaltyAmount: '500–3 000 €',
    links: [{ label: 'e-services.nap.bg', url: 'https://e-services.nap.bg' }],
    legalBasis: 'ЗДДФЛ чл. 50',
    dv: 'ДВ бр. 95/2006',
    publishedAt: '2006-11-24',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'avans-q1',
    title_ru: 'Авансовая вноска КНП — Q1',
    title_bg: 'Авансова вноска ЗКПО — Q1',
    description_ru: 'Първа тримесечна авансова вноска за корпоративен данък за текущата година.',
    authority: 'НАП',
    category: 'advance',
    recurrence: 'annual',
    month: 4,
    day: 15,
    forms: ['ood'],
    penaltyInfo_ru: 'Пеня при просрочке',
    penaltyAmount: 'пеня',
    links: [],
    legalBasis: 'ЗКПО чл. 83',
    dv: 'ДВ бр. 105/2006',
    publishedAt: '2006-12-22',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'zkpo-annual',
    title_ru: 'Годовая декларация ЗКПО',
    title_bg: 'Годишна данъчна декларация ЗКПО',
    description_ru: 'Корпоративная налоговая декларация за прошлый год. Срок — 30 июня. При подаче до 31 марта онлайн — скидка 1% от налога (до 1 000 €).',
    authority: 'НАП',
    category: 'corporate',
    recurrence: 'annual',
    month: 6,
    day: 30,
    forms: ['ood'],
    penaltyInfo_ru: 'Штраф 500–3 000 € + пеня за просрочку уплаты',
    penaltyAmount: '500–3 000 €',
    links: [{ label: 'e-services.nap.bg', url: 'https://e-services.nap.bg' }],
    legalBasis: 'ЗКПО чл. 92',
    dv: 'ДВ бр. 105/2006',
    publishedAt: '2006-12-22',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'gfo-brra-annual',
    title_ru: 'Годовой финансовый отчёт (БРРА)',
    title_bg: 'Годишен финансов отчет в БРРА',
    description_ru: 'Публикация ГФО в Агенция по вписванията (brra.bg). Для малых ООД — до 30 июня. Требуется КЕП или нотариально заверенный документ.',
    authority: 'БРРА',
    category: 'registry',
    recurrence: 'annual',
    month: 6,
    day: 30,
    forms: ['ood'],
    penaltyInfo_ru: 'Штраф 500–2 000 €',
    penaltyAmount: '500–2 000 €',
    links: [{ label: 'brra.bg', url: 'https://brra.bg' }],
    legalBasis: 'ЗСч чл. 40',
    dv: 'ДВ бр. 95/2015',
    publishedAt: '2015-12-08',
    effectiveFrom: '2016-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'avans-q2',
    title_ru: 'Авансовая вноска КНП — Q2',
    title_bg: 'Авансова вноска ЗКПО — Q2',
    description_ru: 'Втора тримесечна авансова вноска за корпоративен данък.',
    authority: 'НАП',
    category: 'advance',
    recurrence: 'annual',
    month: 7,
    day: 15,
    forms: ['ood'],
    penaltyInfo_ru: 'Пеня при просрочке',
    penaltyAmount: 'пеня',
    links: [],
    legalBasis: 'ЗКПО чл. 83',
    dv: 'ДВ бр. 105/2006',
    publishedAt: '2006-12-22',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
  {
    id: 'avans-q3',
    title_ru: 'Авансовая вноска КНП — Q3',
    title_bg: 'Авансова вноска ЗКПО — Q3',
    description_ru: 'Трета тримесечна авансова вноска за корпоративен данък.',
    authority: 'НАП',
    category: 'advance',
    recurrence: 'annual',
    month: 10,
    day: 15,
    forms: ['ood'],
    penaltyInfo_ru: 'Пеня при просрочке',
    penaltyAmount: 'пеня',
    links: [],
    legalBasis: 'ЗКПО чл. 83',
    dv: 'ДВ бр. 105/2006',
    publishedAt: '2006-12-22',
    effectiveFrom: '2007-01-01',
    effectiveTo: null,
    version: '2026-1',
    lastVerified: '2026-01-01',
  },
]

export const CATEGORY_META: Record<EventCategory, {
  label: string
  color: string
  bg: string
}> = {
  vat:         { label: 'ДДС',        color: 'text-blue-700',    bg: 'bg-blue-50 border-blue-200' },
  corporate:   { label: 'КНП/ЗКПО',  color: 'text-violet-700',  bg: 'bg-violet-50 border-violet-200' },
  social:      { label: 'Осигуровки', color: 'text-orange-700',  bg: 'bg-orange-50 border-orange-200' },
  statistical: { label: 'НСИ',        color: 'text-red-700',     bg: 'bg-red-50 border-red-200' },
  registry:    { label: 'БРРА',       color: 'text-emerald-700', bg: 'bg-emerald-50 border-emerald-200' },
  kep:         { label: 'КЕП',        color: 'text-amber-700',   bg: 'bg-amber-50 border-amber-200' },
  salary:      { label: 'Заплати',    color: 'text-cyan-700',    bg: 'bg-cyan-50 border-cyan-200' },
  advance:     { label: 'Авансови',   color: 'text-purple-700',  bg: 'bg-purple-50 border-purple-200' },
  other:       { label: 'Друго',      color: 'text-slate-700',   bg: 'bg-slate-50 border-slate-200' },
}
