import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useUserStore } from '../store/userStore'
import type { AppLanguage } from '../store/userStore'

type DocLang = 'bg' | AppLanguage

const TRANSLATIONS: Record<AppLanguage, {
  backHome: string
  title: string
  subtitle: string
  disclaimerTitle: string
  translationHint: string
  tabs: { bg: string; ru: string; uk: string; en: string }
}> = {
  ru: {
    backHome: 'На главную',
    title: 'Условия использования',
    subtitle: 'Официальная версия — на болгарском языке. Ниже — перевод для удобства.',
    disclaimerTitle: '⚠ Дисклеймер об ответственности',
    translationHint: 'Перевод носит информационный характер. В случае расхождений приоритет имеет болгарский текст.',
    tabs: { bg: 'Български (официален)', ru: 'Русский', uk: 'Українська', en: 'English' },
  },
  uk: {
    backHome: 'На головну',
    title: 'Умови використання',
    subtitle: 'Офіційна версія — болгарською мовою. Нижче — переклад для зручності.',
    disclaimerTitle: '⚠ Дисклеймер про відповідальність',
    translationHint: 'Переклад має інформаційний характер. У разі розбіжностей пріоритет має болгарський текст.',
    tabs: { bg: 'Български (офіційний)', ru: 'Русский', uk: 'Українська', en: 'English' },
  },
  en: {
    backHome: 'Home',
    title: 'Terms of Service',
    subtitle: 'The official version is in Bulgarian. A translation is provided below for convenience.',
    disclaimerTitle: '⚠ Liability disclaimer',
    translationHint: 'The translation is informational only. In case of discrepancies the Bulgarian text prevails.',
    tabs: { bg: 'Български (official)', ru: 'Русский', uk: 'Українська', en: 'English' },
  },
  bg: {
    backHome: 'Начало',
    title: 'Общи условия за ползване',
    subtitle: 'Официалният текст е на български език.',
    disclaimerTitle: '⚠ Отказ от отговорност',
    translationHint: 'Преводът е с информативен характер. При разминавания български текст има предимство.',
    tabs: { bg: 'Български (официален)', ru: 'Русский', uk: 'Українська', en: 'English' },
  },
}

const DISCLAIMER_BG = `TaxBG Pro е информационен помощник. Системата помага за водене на отчетност и контрол на срокове, но НЕ носи юридическа отговорност за:
• верността на въведените от потребителя данни;
• спазването на данъчните срокове;
• правилността на данъчни декларации, подадени на база данни от системата;
• решения, взети на база информация от системата;
• отговори, генерирани от AI асистента.

Отговорността за счетоводната отчетност и данъчните задължения е на управителя на предприятието (ЗСч чл. 10) и/или на лицензирания счетоводител.

Потребителят се задължава да проверява всяка генерирана декларация, отчет или документ преди подаване в НАП, НОИ, БРРА или друг държавен орган.`

const DISCLAIMER_RU = `TaxBG Pro — это информационный помощник. Система помогает вести учёт и контролировать сроки, но НЕ несёт юридической ответственности за:
• корректность введённых пользователем данных;
• соблюдение налоговых сроков;
• правильность налоговых деклараций, поданных на основании данных системы;
• решения, принятые на основе информации из системы;
• ответы, сгенерированные AI-ассистентом.

Ответственность за бухгалтерскую отчётность и налоговые обязательства лежит на управляющем предприятия (ст. 10 ЗСч) и/или лицензированном бухгалтере.

Пользователь обязан проверять каждую сгенерированную декларацию, отчёт или документ перед подачей в НАП, НОИ, БРРА или иной государственный орган.`

const DISCLAIMER_UK = `TaxBG Pro — інформаційний помічник. Система допомагає вести облік та контролювати терміни, але НЕ несе юридичної відповідальності за:
• правильність введених користувачем даних;
• дотримання податкових термінів;
• правильність податкових декларацій, поданих на підставі даних системи;
• рішення, прийняті на основі інформації системи;
• відповіді, згенеровані AI-асистентом.

Відповідальність за бухгалтерський облік та податкові зобов'язання лежить на керівнику підприємства (ст. 10 ЗСч) та/або ліцензованому бухгалтері.

Користувач зобов'язаний перевіряти кожну згенеровану декларацію, звіт або документ перед поданням до НАП, НОІ, БРРА або іншого державного органу.`

const DISCLAIMER_EN = `TaxBG Pro is an informational assistant. The system helps with bookkeeping and deadline tracking but bears NO legal responsibility for:
• the accuracy of data entered by the user;
• compliance with tax deadlines;
• the correctness of tax returns filed based on data from the system;
• decisions taken based on information from the system;
• responses generated by the AI assistant.

Responsibility for accounting records and tax obligations lies with the manager of the enterprise (Art. 10 ЗСч) and/or the licensed accountant.

The user is required to verify every generated declaration, report, or document before submitting it to NRA (НАП), NSSI (НОИ), Commercial Register (БРРА) or any other public authority.`

const DISCLAIMERS: Record<DocLang, string> = {
  bg: DISCLAIMER_BG,
  ru: DISCLAIMER_RU,
  uk: DISCLAIMER_UK,
  en: DISCLAIMER_EN,
}

const BG_TEXT = `
1. Общи положения

TaxBG Pro е информационна система за подпомагане на счетоводния отчет, контрола на срокове и управлението на документи на малки и средни предприятия в Република България. TaxBG Pro НЕ е счетоводна кантора, НЕ предоставя счетоводни услуги по смисъла на Закона за счетоводството и НЕ замества лицензиран счетоводител.

Използването на TaxBG Pro се осъществява на базата на настоящите Общи условия, които имат силата на договор между потребителя и администратора на услугата. С регистрация в системата потребителят декларира, че е прочел, разбрал и приема тези условия.

2. Отказ от отговорност

(Виж отделния раздел „Отказ от отговорност" по-горе — представлява неразделна част от настоящите Общи условия.)

3. Използване на изкуствен интелект (AI Act)

Системата използва изкуствен интелект (AI) в следните функции:
• автоматично генериране на счетоводни проводки от транзакции (по Националния сметкоплан);
• AI асистент за отговори на въпроси (при наличие на конфигуриран API ключ);
• генериране на обяснителни записки и отговори за данъчни проверки.

AI-генерираното съдържание е маркирано с ясен индикатор („🤖 AI"). Потребителят е длъжен да проверява всяко AI-генерирано съдържание преди използване. AI НЕ взема самостоятелни решения — всички действия изискват потвърждение от човек. Настоящата функционалност попада в категорията „AI система с ограничен риск" по смисъла на чл. 50 от Регламент (ЕС) 2024/1689 (AI Act) и е предмет на задължение за прозрачност. За повече информация — вж. /ai-disclosure.

4. Отговорност за данните

Потребителят отговаря изцяло за верността, пълнотата и законосъобразността на данните, които въвежда в системата. TaxBG Pro не проверява фактическата вярност на транзакции, фактури, трудови възнаграждения, ЕГН на служители и други въведени данни. Системата действа като инструмент — отговорността за входа и изхода на данни остава на потребителя.

5. Съхранение на данни

TaxBG Pro съхранява данните на своите сървъри не повече от 1 (една) година. Системата НЕ е дългосрочен архив. Потребителят е длъжен сам да изтегля и съхранява всички счетоводни, кадрови и данъчни документи за срока, изискуем от закона (включително 10-годишния срок по ЗСч и 50-годишния срок за ведомости и осигурителни документи). За целта се използва функцията „Експорт" в раздел /vault.

6. Прекратяване

Потребителят може по всяко време да поиска изтриване на акаунта си от раздел „Настройки". При постъпване на заявка за изтриване:
• на потребителя се предоставят 90 (деветдесет) дни за изтегляне на архив на всички въведени данни;
• след изтичане на 90-дневния срок данните за акаунта се заличават с изключение на:
 • данни, които по закон трябва да се съхраняват за по-дълъг срок (напр. зарплатни ведомости — 50 години), които остават в анонимизиран или псевдонимизиран вид, доколкото това е технически възможно;
• заявката за изтриване може да бъде отменена от потребителя по всяко време в рамките на 90-дневния срок.

Администраторът на услугата може едностранно да прекрати достъпа до услугата при грубо нарушение на настоящите условия, при използване на услугата за измама, злоупотреба или противозаконни цели.

7. Промени в условията

Администраторът на услугата си запазва правото да изменя настоящите Общи условия. За значими изменения потребителите се уведомяват чрез email или при първо следващо влизане в системата. Продължаването на използването на услугата след нотификация се счита за приемане на новата редакция.

8. Интелектуална собственост

Софтуерът, текстовете, дизайнът и базата знания на TaxBG Pro са обект на авторско право. Не се разрешава копиране, разпространение или използване за комерсиални цели без писмено съгласие.

9. Приложимо право и подсъдност

За всички въпроси, неуредени от настоящите Общи условия, се прилага законодателството на Република България. Всички спорове, произтичащи от или във връзка с използването на услугата, се разглеждат от компетентния съд в гр. София.

10. Контакт

За въпроси по настоящите условия: {{CONTACT_EMAIL}}.
`.trim()

const RU_TEXT = `
1. Общие положения

TaxBG Pro — информационная система для помощи в ведении бухгалтерского учёта, контроля сроков и управления документами малых и средних предприятий Республики Болгария. TaxBG Pro НЕ является бухгалтерской фирмой, НЕ оказывает бухгалтерских услуг и НЕ заменяет лицензированного бухгалтера.

2. Отказ от ответственности

(См. отдельный блок "Отказ от ответственности" выше — неотъемлемая часть настоящих Условий.)

3. Использование ИИ (AI Act)

Система использует ИИ для:
• автоматического формирования проводок (Национальный план счетов Болгарии);
• AI-ассистента (при наличии API-ключа);
• генерации пояснительных записок и ответов на проверки НАП.

AI-контент помечен индикатором "🤖 AI". Пользователь обязан проверять каждый AI-ответ. ИИ не принимает решений самостоятельно. Система относится к категории "AI с ограниченным риском" (ст. 50 Регламента (ЕС) 2024/1689 / AI Act) и подлежит обязательству прозрачности. См. /ai-disclosure.

4. Ответственность за данные

Пользователь полностью отвечает за корректность и полноту введённых данных. TaxBG Pro не проверяет фактическую достоверность транзакций, счетов, зарплат, ЕГН сотрудников.

5. Хранение данных

TaxBG Pro хранит данные на своих серверах не более 1 (одного) года. Система НЕ является долгосрочным архивом. Пользователь обязан самостоятельно скачивать и хранить документы в течение установленного законом срока (10 лет — бухгалтерские, 50 лет — ведомости) через раздел /vault.

6. Прекращение

Пользователь может в любой момент запросить удаление аккаунта в "Настройках". При запросе:
• предоставляется 90 дней для скачивания архива;
• по истечении 90 дней данные удаляются, за исключением тех, которые должны храниться по закону (обезличиваются, насколько это технически возможно);
• запрос можно отменить в любой момент в течение 90 дней.

Администратор вправе прекратить доступ при грубом нарушении условий или злоупотреблении.

7. Изменения условий

Администратор вправе изменять Условия. О существенных изменениях пользователь уведомляется по email или при следующем входе.

8. Интеллектуальная собственность

ПО, тексты, дизайн и база знаний TaxBG Pro охраняются авторским правом.

9. Применимое право и подсудность

Применяется законодательство Республики Болгария. Споры — в компетентном суде г. София.

10. Контакт

{{CONTACT_EMAIL}}
`.trim()

const UK_TEXT = `
1. Загальні положення

TaxBG Pro — інформаційна система для підтримки бухгалтерського обліку, контролю термінів та управління документами малих і середніх підприємств Республіки Болгарія. TaxBG Pro НЕ є бухгалтерською фірмою, НЕ надає бухгалтерських послуг і НЕ замінює ліцензованого бухгалтера.

2. Відмова від відповідальності

(Див. окремий блок "Відмова від відповідальності" вище.)

3. Використання ШІ (AI Act)

Система використовує ШІ для:
• автоматичного формування проводок (Національний план рахунків Болгарії);
• AI-асистента (за наявності API-ключа);
• генерації пояснювальних записок та відповідей на перевірки НАП.

AI-контент позначено індикатором "🤖 AI". Користувач зобов'язаний перевіряти кожну AI-відповідь. Система належить до категорії "ШІ з обмеженим ризиком" (ст. 50 Регламенту (ЄС) 2024/1689 / AI Act). Див. /ai-disclosure.

4. Відповідальність за дані

Користувач повністю відповідає за достовірність введених даних. TaxBG Pro не перевіряє фактичну достовірність транзакцій, рахунків, зарплат, ЄГН.

5. Зберігання даних

TaxBG Pro зберігає дані на своїх серверах не більше 1 року. Користувач зобов'язаний самостійно завантажувати та зберігати документи відповідно до термінів, встановлених законом (10 років — бухгалтерські; 50 років — відомості та документи стажу) через розділ /vault.

6. Припинення

Користувач може будь-коли запитати видалення акаунта в "Налаштуваннях". 90 днів надається на завантаження архіву, після чого дані видаляються (крім тих, які закон вимагає зберігати довше — вони знеособлюються). Запит можна скасувати протягом 90 днів.

7. Зміни умов

Адміністратор має право змінювати Умови та сповіщає про суттєві зміни електронною поштою або при наступному вході.

8. Інтелектуальна власність

ПЗ, тексти, дизайн та база знань TaxBG Pro охороняються авторським правом.

9. Застосовне право та підсудність

Застосовується законодавство Республіки Болгарія. Спори — у компетентному суді м. Софія.

10. Контакт

{{CONTACT_EMAIL}}
`.trim()

const EN_TEXT = `
1. General

TaxBG Pro is an informational system supporting bookkeeping, deadline tracking and document management for small and medium enterprises in the Republic of Bulgaria. TaxBG Pro is NOT an accounting firm, does NOT provide accounting services within the meaning of the Bulgarian Accounting Act, and does NOT replace a licensed accountant.

2. Liability Disclaimer

(See the separate "Liability disclaimer" block above — it forms an integral part of these Terms.)

3. Use of AI (AI Act)

The system uses AI for:
• automatic generation of accounting entries from transactions (Bulgarian National Chart of Accounts);
• an AI assistant (when an API key is configured);
• generating explanatory notes and responses to tax audits.

AI-generated content is clearly labelled ("🤖 AI"). The user is required to verify every AI-generated item before use. AI does not make autonomous decisions. This system falls under the "limited-risk AI system" category of Art. 50 of Regulation (EU) 2024/1689 (AI Act) and is subject to transparency obligations. See /ai-disclosure.

4. Responsibility for Data

The user is fully responsible for the accuracy and completeness of the data entered. TaxBG Pro does not verify the factual correctness of transactions, invoices, salaries, or employee ID numbers.

5. Data Storage

TaxBG Pro stores data on its servers for no more than 1 (one) year. The system is NOT a long-term archive. The user is required to download and store all accounting, payroll and tax documents for the statutory retention period (10 years for accounting records, 50 years for payroll and social-security records) using the Export / /vault feature.

6. Termination

The user may request account deletion at any time from Settings. Upon request:
• 90 (ninety) days are provided for downloading a full archive;
• after 90 days the account data is erased, except for data which by law must be retained for a longer period (which is anonymised or pseudonymised to the extent technically feasible);
• the deletion request can be cancelled at any time within the 90-day period.

The operator may terminate access in case of gross breach or abuse.

7. Changes

The operator may amend these Terms. Material changes are notified by email or at next login.

8. Intellectual Property

The software, texts, design and knowledge base of TaxBG Pro are protected by copyright.

9. Governing Law

These Terms are governed by the law of the Republic of Bulgaria. Disputes are subject to the jurisdiction of the competent court in Sofia.

10. Contact

{{CONTACT_EMAIL}}
`.trim()

const BODIES: Record<DocLang, string> = {
  bg: BG_TEXT,
  ru: RU_TEXT,
  uk: UK_TEXT,
  en: EN_TEXT,
}

export default function Terms() {
  const language = useUserStore((s) => s.language)
  const ui = TRANSLATIONS[language] ?? TRANSLATIONS.ru
  const [tab, setTab] = useState<DocLang>('bg')

  return (
    <div className="min-h-screen px-4 py-10" style={{ backgroundColor: 'var(--surface)' }}>
      <div className="mx-auto max-w-3xl">
        <div className="mb-6 flex items-center justify-between text-sm">
          <Link to="/" className="text-blue-600 hover:underline">{ui.backHome}</Link>
          <Link to="/privacy" className="text-slate-500 hover:underline">Privacy</Link>
        </div>

        <h1 className="text-3xl font-bold text-slate-800">{ui.title}</h1>
        <p className="mt-2 text-sm text-slate-500">{ui.subtitle}</p>

        <div className="mt-6 rounded-lg border-2 border-red-300 bg-red-50 p-5 shadow-sm">
          <h2 className="text-lg font-bold text-red-800">{ui.disclaimerTitle}</h2>
          <p className="mt-3 whitespace-pre-wrap text-sm font-medium leading-relaxed text-red-900">
            {DISCLAIMERS[tab]}
          </p>
        </div>

        <div className="mt-6 flex flex-wrap gap-2 border-b border-slate-200">
          {(['bg', 'ru', 'uk', 'en'] as DocLang[]).map((code) => (
            <button
              key={code}
              type="button"
              onClick={() => setTab(code)}
              className={`-mb-px border-b-2 px-3 py-2 text-sm transition-colors ${
                tab === code
                  ? 'border-blue-600 text-blue-700 font-medium'
                  : 'border-transparent text-slate-500 hover:text-slate-700'
              }`}
            >
              {ui.tabs[code]}
            </button>
          ))}
        </div>

        {tab !== 'bg' && (
          <p className="mt-4 rounded-md border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
            {ui.translationHint}
          </p>
        )}

        <article className="mt-6 whitespace-pre-wrap rounded-lg border border-slate-200 bg-white p-6 text-[0.92rem] leading-relaxed text-slate-800 shadow-sm">
          {BODIES[tab]}
        </article>

        <p className="mt-6 text-xs text-slate-400">© 2026 TaxBG Pro</p>
      </div>
    </div>
  )
}
